localRepositories:
  gradle-prod-local:
      type: gradle
      description: "production deployment"
      xray:
        enabled: true
  gradle-release-local:
      type: gradle
      description: "release build"
      xray:
        enabled: true
  tomcat-local:
      type: generic
      description: "approved copy"
      repoLayout: simple-default
      xray:
        enabled: true
  docker-local:
      type: docker
      repoLayout: simple-default
      description: "docker development repo"
      xray:
        enabled: true
  docker-prod-local:
      type: docker
      repoLayout: simple-default
      description: "production deployment"
      xray:
        enabled: true
  docker-stage-local:
      type: docker
      repoLayout: simple-default
      description: "staging deployment"
      xray:
        enabled: true
  libs-release-local:
      type: maven
      repoLayout: maven-2-default
      description: "maven release libraries"
      xray:
        enabled: true
  helm-local:
      type: helm
      repoLayout: simple-default
      description: "helm local "
      xray:
        enabled: true
  generic-local:
      type: generic
      repoLayout: simple-default
      description: "generic local"
      xray:
        enabled: true
remoteRepositories:
  docker-remote:
      type: docker
      url: https://registry-1.docker.io
      repoLayout: simple-default
      xray:
        enabled: true
  helm-remote:
      type: helm
      url: https://storage.googleapis.com/kubernetes-charts
      repoLayout: simple-default
      xray:
        enabled: true
virtualRepositories:
  gradle-release:
      type: gradle
      repositories:
        - gradle-release-local
        - jcenter
        - gradle-prod-local
      description: "gradle virtual repositories"
      defaultDeploymentRepo: gradle-release-local
  docker-virtual:
      type: docker
      repositories:
        - docker-local
        - docker-remote
        - docker-dev-local
        - docker-prod-local
        - docker-stage-local
      description: "docker virtual"
      defaultDeploymentRepo: docker-stage-local
  libs-release:
      type: maven
      repositories:
        - libs-release-local
        - jcenter
      description: "maven libraries virtual"
      defaultDeploymentRepo: libs-release-local
  helm-virtual:
      type: helm
      repositories:
        - helm-local
        - helm-remote
      description: "helm virtual"
      defaultDeploymentRepo: helm-local

